# Site settings
name: PM2 Documentation
email: contact@keymetrics.io

# Build settings
sass:
  style: compact

markdown: kramdown

gems:
  - jekyll-redirect-from

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 parse_block_html: true

 # syntax_highlighter: rouge
repository: 'keymetrics/doc-pm2'
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-feed
# keep_files: [images]
baseurl: "/doc"
destination: docs
exclude: ["node_modules","README.md", "gulpfile.js", "package.json", "package-lock.json", "yarn.lock"]

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico","assets", "CNAME", "node_modules", "package.json", "package-lock.json","_src","_docs","gulpfile.js"]
